### ISSUE TITLE
matchesReferenceImage not working 

### ISSUE THREAD

**Issue by omarfares95** [MohabMohie/using_SHAFT_ENGINE#51]
java.lang.UnsatisfiedLinkError: 'long org.opencv.core.Mat.n_Mat()'
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:23)
	at org.opencv.core.MatOfByte.<init>(MatOfByte.java:34)
	at com.shaft.gui.image.ImageProcessingActions.attemptToFindImageUsingOpenCV(ImageProcessingActions.java:241)
	at com.shaft.gui.image.ImageProcessingActions.findImageWithinCurrentPage(ImageProcessingActions.java:338)
	at com.shaft.gui.image.ImageProcessingActions.compareAgainstBaseline(ImageProcessingActions.java:379)
	at com.shaft.validation.ValidationsHelper.validateElementMatches(ValidationsHelper.java:497)
	at com.shaft.validation.ValidationsExecutor.perform(ValidationsExecutor.java:147)
	at TestPackage.TestClass.testMethod2(TestClass.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
this error appear when start using matchesReferenceImage

OS : MAC 

@Test
    public void testMethod2() {
        By googleLogo_image = By.xpath("//img[@alt='Google']");
        Validations.assertThat()
                .element(driver, googleLogo_image)
                .matchesReferenceImage()
                .withCustomReportMessage("assert that the logo image is displayed properly")
                .perform();
    }

**Comment by MohabMohie** [comment]
Please submit this to the engine project itself.
